### ISSUE TITLE
Can I connect the xbox controller directly to the Amiga wirelessly?

### ISSUE THREAD

**Issue by shaoshuaizyk** [farm-ng/amiga-xbox-controller#2]
Hello, I am trying to run this code to control the amiga with xbox controller. I have two questions:
1. Can I connect the xbox controller directly to the amiga wirelessly and control it?
2. Did you try to run it on MAC system instead of linux?

Best Regard

**Comment by edgarriba** [comment]
hi @shaoshuaizyk 

> Can I connect the xbox controller directly to the amiga wirelessly and control it?

In principle yes, but you need to contact `support@farm-ng.com` in order to get some help to install the [`xow`](https://github.com/medusalix/xow) driver directly in the amiga brain because we don't expose `systemcl` which is required as part of the driver install process.

> Did you try to run it on MAC system instead of linux?

We haven't tried but happy to hear your experience and help to make it happen. In theory  `xow` is for Linux (as they describe in the Readme), so we might have to find an alternative to Mac.

**Comment by Hackerman342** [comment]
Closing as a stale request.

@shaoshuaizyk please let us know if the xbox controller plugged into the amiga directly for wireless control is a priority/need and we can re-open.

For running on Mac, I believe you should be able to find open source information on connecting an xbox controller.
